### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [postajob/gtm_application#1]
Thank you for submitting template to the gallery. However, there are a few issues that needs to be resolved ahead of approving the template for the gallery.

1) The SHA hash in manifest should be the latest version or the one which has all the changes in place. We recommend to use the value which has final changes in place.
2) The documentation link provided in manifest file [http://postajob.io/gtm](http://postajob.io/gtm) is not valid. We are seeing "404 page not found error". Please resolve the issue.

**Comment by goffle** [comment]
Update Sha
Fixed documentation link
